[package]
name = 'subscription'
version = '1.0.0'

[addresses]
Subscription = "0x6234710dfe797ec0d6196b1c6a46af2eddb82e94a9258e05e0447c502b9ac441"

[dependencies.AptosFramework]
git = 'https://github.com/dhruvja/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
